config/routes.rb
Rails.application.routes.draw do
  
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	devise_scope :user do
  	get "/" => "devise/sessions#new"
	end

  root :to => "devise/sessions#new"

  resources :projects, :shallow => true do
  	resources :comments, only: [:index, :create]
  end

  namespace :admin do
    resources :projects
    resources :users, only: [:index, :destroy]
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project, optional: true
  belongs_to :user

  validates :body, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::AdminController
  #before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @comments = Comment.all.order(:id)
  end

  def edit

  end

  def update

    @comment = Comment.find(params[:id])

    if @comment.update_attributes(comment_params)
      flash[:notice] = t("flash.message.comment.update")
      redirect_to admin_comments_path
    else
      render action: :edit
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = t("flash.message.comment.destroy")
    redirect_to admin_comments_path
  end


  private
  
  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user!
  load_and_authorize_resource :project
  load_and_authorize_resource :comment, through: :project

	def index
    @comments = Comment.where(project_id: params[:project_id]).accessible_by(current_ability)
  end

  def create
    @project = Project.find( params[:project_id] )
    @comment = @project.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
        if @comment.save
          format.html { redirect_to projects_path, notice: "Comment successfully created!" }
          format.json  { render json: @comment, include: [:user] }
        else
          format.html { render :new }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
    end

  end

  private
	  # Never trust parameters from the scary internet, only allow the white list through.
	  def comment_params
	    params.require(:comment).permit(:body, :project_id, :user_id)
	  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/admin/comments/_form.html.erb
<!-- Begin block container -->
<div class="block block-bordered block-rounded">
  <!-- Begin block header -->
  <div class="block-header">
    <h2 class="block-title"><%= t('.title') %></h2>
  </div>
  <!-- End block header -->
  <!-- Begin block content -->
  <div class="block-content">
    <%= form_with(model: comment, url: admin_comment_path, local: true) do |form| %>
      <%= errors_for(comment) %>
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, id: :comment_body, class:"form-control", rows: 10 %>
      </div>

      <div class="push-10-t text-center">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <!-- End block content -->
</div>
<!-- End block container -->

app/views/admin/comments/edit.html.erb
<%= render 'form', comment: @comment %>

app/views/admin/comments/index.html.erb
<div class="block block-bordered block-rounded">
  <div class="block-header">
    <h3 class="block-title"><%= t('.title') %></h2>
  </div>
  <div class="block-content">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t('.project')%></th>
          <th style="width: 60%;"><%=t('.comment')%></th>
          <th><%= t('.user')%></th>
          <th style="width: 100px;" class="text-center"><%= t('.actions') %></th>
        </tr>
      </thead>
      <tbody>
        <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.project.name%>
          <td><%= comment.body %></td>
          <td><%= comment.user.fullname %></td>
          <td class="text-center">
            <span class="pull-left">
            <%= link_to t('.edit'), edit_admin_comment_path(comment) %>
            </span>
            <span class="pull-right">
            <%= link_to t('.destroy'), admin_comment_path(comment), method: :delete, data: { confirm: t('.confirm') } %>
            </span>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>