config/routes.rb
Rails.application.routes.draw do
  
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	devise_scope :user do
  	get "/" => "devise/sessions#new"
	end

  root :to => "devise/sessions#new"

  resources :projects, :shallow => true do
  	resources :comments, only: [:index, :create]
  end

  namespace :admin do
    resources :projects
    resources :users, only: [:index, :destroy]
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  
  enum status: [:created, :started, :stopped, :completed]
  belongs_to :user
  has_many :comments, :dependent => :destroy

  validates :name, :description, :estimated_effort, :actual_effort, :status, presence: true
  validates_inclusion_of :is_public, :in => [true, false]
  validates_inclusion_of :estimated_effort, :actual_effort, :in => 1..10
  validates_numericality_of :estimated_effort, :actual_effort, only_integer: true, :in => 1..10

  after_destroy :broadcast_delete

  def broadcast_delete
    ActionCable.server.broadcast 'projects', response: 'deleted', id: id
  end
  
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  #before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @projects = Project.all.order(:id)
  end

  def edit

  end

  def update

    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      flash[:notice] = t("flash.message.project.update")
      redirect_to admin_projects_path
    else
      render action: :edit
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = t("flash.message.project.destroy")
    redirect_to admin_projects_path
  end

  private
  
    def project_params
        params.require(:project).permit(:name, :description)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @projects = Project.all.accessible_by(current_ability).order(:id)
    @comments = Comment.new
  end

  def show
    Project.includes(:comments).find(params[:id])
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      flash[:notice] = t("flash.message.project.create")
      redirect_to projects_path
    else
      render :new
    end
  end

  def update
    current_user_role = current_user.role
    current_user_id = current_user.id
    project_owner_id = @project.user_id

    respond_to do |format|
      if @project.update(UserParams.build(params, current_user_role, current_user_id, project_owner_id))
        format.html { redirect_to projects_path, notice: t("flash.message.project.update") }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  class UserParams
    def self.build (params, current_user_role, current_user_id, project_owner_id)
      if current_user_role == "user" && current_user_id != project_owner_id  
          params.require(:project).permit(:description, :status)
        else
          params.require(:project).permit(:name, :description, :is_public, :estimated_effort, :actual_effort, :status)
        end
    end
  end


  private
  
    def project_params
        params.require(:project).permit(:name, :description, :is_public, :estimated_effort, :actual_effort, :status, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def is_owner?
		if action_name == "edit" 
			if current_user.id == @project.user.id
				true
			else
				false
			end
		else
			true
		end
	end
end

app/views/admin/projects/_form.html.erb
<!-- Begin block container -->
<div class="block block-bordered block-rounded">
  <!-- Begin block header -->
  <div class="block-header">
    <h2 class="block-title"><%= t('.title') %></h2>
  </div>
  <!-- End block header -->
  <!-- Begin block content -->
  <div class="block-content">
    <%= form_with(model: project, url: admin_project_path, local: true) do |form| %>
      <%= errors_for(project) %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, id: :project_name, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, id: :project_description, class:"form-control", rows: 5%>
      </div>

      <div class="push-10-t text-center">
        <%= form.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  <!-- End block content -->
</div>
<!-- End block container -->

app/views/admin/projects/edit.html.erb
<%= render 'form', project: @project %>

app/views/admin/projects/index.html.erb
<div class="block block-bordered block-rounded">
  <div class="block-header">
    <h3 class="block-title"><%= t('.title') %></h2>
  </div>
  <div class="block-content">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t('.name') %></th>
          <th style="width: 60%;"><%= t('.description') %></th>
          <th><%= t('.owner') %></th>
          <th style="width: 100px;" class="text-center"><%= t('.actions') %></th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td width="400px"><%= project.description.first(150) %></td>
          <td><%= project.user.fullname %></td>
          <td class="text-center">
            <span class="pull-left">
              <%= link_to t('.edit'), edit_admin_project_path(project) %>
            </span>
            <span class="pull-right">
            <%= link_to t('.destroy'), admin_project_path(project), method: :delete, data: { confirm: t('.confirm') } %>
            </span>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>