config/routes.rb
Rails.application.routes.draw do
  
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	devise_scope :user do
  	get "/" => "devise/sessions#new"
	end

  root :to => "devise/sessions#new"

  resources :projects, :shallow => true do
  	resources :comments, only: [:index, :create]
  end

  namespace :admin do
    resources :projects
    resources :users, only: [:index, :destroy]
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  
  enum status: [:created, :started, :stopped, :completed]
  belongs_to :user
  has_many :comments, :dependent => :destroy

  validates :name, :description, :estimated_effort, :actual_effort, :status, presence: true
  validates_inclusion_of :is_public, :in => [true, false]
  validates_inclusion_of :estimated_effort, :actual_effort, :in => 1..10
  validates_numericality_of :estimated_effort, :actual_effort, only_integer: true, :in => 1..10

  after_destroy :broadcast_delete

  def broadcast_delete
    ActionCable.server.broadcast 'projects', response: 'deleted', id: id
  end
  
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  #before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @projects = Project.all.order(:id)
  end

  def edit

  end

  def update

    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      flash[:notice] = t("flash.message.project.update")
      redirect_to admin_projects_path
    else
      render action: :edit
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = t("flash.message.project.destroy")
    redirect_to admin_projects_path
  end

  private
  
    def project_params
        params.require(:project).permit(:name, :description)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @projects = Project.all.accessible_by(current_ability).order(:id)
    @comments = Comment.new
  end

  def show
    Project.includes(:comments).find(params[:id])
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      flash[:notice] = t("flash.message.project.create")
      redirect_to projects_path
    else
      render :new
    end
  end

  def update
    current_user_role = current_user.role
    current_user_id = current_user.id
    project_owner_id = @project.user_id

    respond_to do |format|
      if @project.update(UserParams.build(params, current_user_role, current_user_id, project_owner_id))
        format.html { redirect_to projects_path, notice: t("flash.message.project.update") }
        format.json { head :no_content }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  class UserParams
    def self.build (params, current_user_role, current_user_id, project_owner_id)
      if current_user_role == "user" && current_user_id != project_owner_id  
          params.require(:project).permit(:description, :status)
        else
          params.require(:project).permit(:name, :description, :is_public, :estimated_effort, :actual_effort, :status)
        end
    end
  end


  private
  
    def project_params
        params.require(:project).permit(:name, :description, :is_public, :estimated_effort, :actual_effort, :status, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
	def is_owner?
		if action_name == "edit" 
			if current_user.id == @project.user.id
				true
			else
				false
			end
		else
			true
		end
	end
end

app/views/projects/_form.html.erb
<div class="col-md-8 col-md-offset-2 push-10-t">
  <!-- Begin block container -->
  <div class="block block-bordered block-rounded">
    <!-- Begin block header -->
    <div class="block-header">
      <h2 class="block-title"><%= t('.title') %></h2>
    </div>
    <!-- End block header -->
    <!-- Begin block content -->
    <div class="block-content">
      <%= form_with(model: project, local: true) do |form| %>
        <%= errors_for(project) %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, id: :project_name, class:"form-control", disabled: !is_owner? %>
        </div>

        <div class="form-group">
          <%= form.label :description %>
          <%= form.text_area :description, id: :project_description, class:"form-control", rows: 5%>
        </div>

        <div class="form-group">
          <%= form.label :estimated_effort %>
          <%= form.text_field :estimated_effort, id: :project_estimated_effort, class:"form-control", disabled: !is_owner?%>
        </div>

        <div class="form-group">
          <%= form.label :actual_effort %>
          <%= form.text_field :actual_effort, id: :project_actual_effort, class:"form-control", disabled: !is_owner?%>
        </div>

        <div class="form-group">
          <%= form.label :visibility %><br />
          <%= form.label :is_public, "public", :value => "true"  %>
          <%= form.radio_button :is_public, true, disabled: !is_owner?%>
          <%= form.label :is_public, "private", :value => "false", class: "push-10-l"%>
          <%= form.radio_button :is_public, false, disabled: !is_owner?%>
        </div>

        <div class="form-group">
          <%= form.label :status %><br>
          <%= form.select :status, Project.statuses.keys, {}, {class:"form-control"} %>
        </div>

        <div class="push-10-t text-center">
          <%= form.submit class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <!-- End block content -->
  </div>
  <!-- End block container -->
</div>

app/views/projects/_project.html.erb
<div class="col-md-8 col-md-offset-2" data-project-id="<%= project.id%>">
	<!-- Begin block container -->
  <div class="block block-bordered block-rounded">
  	<!-- Begin block header -->
    <div class="block-header">
      <div class="row">
        <div class="col-sm-7">
          <h2 class="block-title">
            <% if project.is_public %>
              <i class="glyphicon glyphicon-star push-5-r green-icon"></i>
            <% else %>
              <i class="glyphicon glyphicon-star push-5-r red-icon"></i>
            <% end %>
            <%= project.name %>
          </h2>
        </div>
        <div class="col-sm-5">
          <table class="table-bordered block-table text-center">
            <tbody>
              <tr>
                <td class="col-sm-6 <%= project.status %>">
                  <%= project.status.capitalize %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- End block header -->

    <!-- Begin block content -->
    <div class="block-content">
    	<div class="row">
        <div class="col-sm-7">
	        <i class="glyphicon glyphicon-user"></i>
	        <span class="push-5-l push-5-r"><%= project.user.fullname %></span>
	        <i class="glyphicon glyphicon-time"></i>
	        <span class="push-5-l push-5-r">
		    		<%= time_ago_in_words(project.created_at) %>
		    	</span>
        </div>
      </div>

      <div class="row push-10-t">
        <div class="col-sm-7">
          <div>
            <%= project.description %>
          </div>
        </div>
        <div class="col-sm-5">
          <table class="table-bordered block-table bg-gray-lighter text-center">
            <tbody>
              <tr>
                <td class="col-sm-6">
                  <div>Estimated level of effort</div>
                  <div class="h1">
                    <%= project.estimated_effort %>
                  </div>
                </td>
                <td class="col-sm-6">
                  <div>Actual level of effort</div>
                  <div class="h1">
                    <%= project.actual_effort %>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!-- End block content -->

    <!-- Begin block comment -->
    <div class="block-comment-header">
      <div class="row">
        <div class="col-sm-7">
          <% if project.is_public? %>
            <%= link_to "javascript:toggle_visibility('block#{project.id}');" do %>
              <i class="glyphicon glyphicon-comment"></i><span class="push-5-l"><%= t('.comments') %></span>
            <% end %>
          <% end %>
        </div>
        <div class="col-sm-5">
          <% if !is_admin? %>
            <%= link_to edit_project_path(project), class:"pull-right" do %>
              <i class="glyphicon glyphicon-edit"></i><span class="push-5-l"><%= t('.modify') %></span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <% if project.is_public? %>
    <div class="block-comment" id="<%="block#{project.id}"%>">
      <div class="row">
        <div class="col-sm-12">
          <%= react_component 'Comment', { project_id: project.id, is_admin: is_admin?  } %>
        </div>
      </div>
    <% end %>  
    </div>
    <!-- End block comment -->
  </div>
  <!-- End block container -->
</div>

app/views/projects/edit.html.erb
<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<% @projects.each do |project| %>
  <%= render 'project', project: project %>
<% end %>

app/views/projects/new.html.erb
<%= render 'form', project: @project %>