config/routes.rb
Rails.application.routes.draw do
  
	devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
	devise_scope :user do
  	get "/" => "devise/sessions#new"
	end

  root :to => "devise/sessions#new"

  resources :projects, :shallow => true do
  	resources :comments, only: [:index, :create]
  end

  namespace :admin do
    resources :projects
    resources :users, only: [:index, :destroy]
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
	before_action :check_authorized

	def check_authorized
    redirect_to projects_path unless current_user.role == "admin"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

	rescue_from CanCan::AccessDenied do |exception|
			session[:last_page] = request.env['HTTP_REFERER']
    	render :file => "#{Rails.root}/public/403.html", :status => 403, :layout => false
    end

	def after_sign_in_path_for(resource)
    	projects_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def is_admin?
		if current_user.role == "admin"
			true
		else
			false
		end
	end

	def errors_for(object)
	    if object.errors.any?
	        content_tag(:div, class: "panel panel-danger") do
	            concat(content_tag(:div, class: "panel-heading") do
	                concat(content_tag(:h4, class: "panel-title") do
	                    concat "#{pluralize(object.errors.count, "error")} prohibited this #{object.class.name.downcase} from being saved:"
	                end)
	            end)
	            concat(content_tag(:div, class: "panel-body") do
	                concat(content_tag(:ul) do
	                    object.errors.full_messages.each do |msg|
	                        concat content_tag(:li, msg)
	                    end
	                end)
	            end)
	        end
	    end
	end

end

app/views/application/_flash_alert.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key == :notice ? "success" : key %>" data-dismiss="alert">
    <a class="close">×</a>
    <%= value %>
    </div>
<% end %>

app/views/application/_header.html.erb
<title>Home Improvement</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <meta charset="utf-8">
  <meta name="description" content="Projet pour Lexop">
  <meta name="author" content="Daniel Gagné">
  
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <%= link_to t('project_title'), projects_path, class: "navbar-brand"%>
      <% else %>
        <span class="navbar-brand" href="/"><%= t('project_title') %></span>
      <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<% if user_signed_in? && !is_admin? %>
      		<li>
              <p class="navbar-btn push-10-l">
                <%= link_to t('project_new'), new_project_path, class: "btn btn-danger  btn-sm"%>
              </p>
          </li>
      	<% end %>
      </ul>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <p class="navbar-btn">
            <% if is_admin? %>
              <%= link_to t('site_admin'), admin_projects_path, class:"btn  btn-warning btn-sm push-5-r" %>
            <% end %>
          </p>
        </li>
        <li>
          <p class="navbar-btn">
            <%= button_to t('sign_out'), destroy_user_session_path, method: "delete", class:"btn  btn-success btn-sm" %>
           </p>    
        </li>
      </ul>
      <% end%>
     </div>
  </div>
</nav>